# -*- coding: utf-8 -*-
{
    'name': "Ejaf Maintenance",
    'summary': "Ejaf Maintenance",
    'description': """
    Customize maintenance request and maintenance equipment.
    """,
    'author': "Ejaf Technology",
    'website': "http://www.ejaftech.com/",
    'depends': ['stock', 'check_list', 'base', 'hr_maintenance', 'ejaf_maintenance_menus'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/data.xml',
        'views/maintenance_request.xml',
        'views/maintenance_request_timeline.xml',
        'views/check_list.xml',
        'views/job_order.xml',
        'views/technical_inspection.xml',
        'views/assets.xml',
        'views/region.xml',
        'views/site_type.xml',
        'views/tower_type.xml',
        'views/od_type.xml',
        'views/fuel_tank_type.xml',
        'views/alternator_model.xml',
        'views/engine_manufacturer.xml',
        'views/battery_manufacturer.xml',
        'views/battery_model.xml',
        'views/rect_brand.xml',
        'views/engine_model.xml',
        'views/fiber_connection.xml',
        'views/ats_model.xml',
        'views/rbs_model.xml',
        'views/rt_type.xml',
        'views/radio_type.xml',
        'views/mmu_type.xml',
        'views/amm_type.xml',
        'views/antenna_type.xml',
        'views/dvr_type.xml',
        'views/problem_category.xml',
        'views/gen_set_manufacturer.xml',
        'views/alternator_manufacturer.xml',
        'views/tower_topology.xml',
        'views/clu_status.xml',
        'views/l_type.xml',
        'views/ne_impacted.xml',
        'views/ne_type.xml',
        'views/maintenance_equipment.xml',
        'views/maintenance_team.xml',
        'views/site_planning_views.xml',
        'views/fuel_planning.xml',
        'views/generator_planning.xml',
        'views/res_config_settings_views.xml',
        'views/menuitems.xml'
    ],
    'demo': [
    ],

}
